### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by molinto** [patricklodder/infusionsoft#8]
Hi, thanks for your repository.  It certainly helps a great deal.

Do you deal with the XML Error codes on the response?
Eg: http://community.infusionsoft.com/showthread.php/453-Infusionsoft-API-Fault-Codes

**Comment by patricklodder** [comment]
XML-RPC "Fault"s are returned as an instance of ```Error``` in the callback, by node-xmlrpc. See https://github.com/baalexander/node-xmlrpc/blob/master/lib/deserializer.js#L81-L90
